### PR TITLE
Zstandard compiles and run on m68k cpus

### LINKED ISSUE #2756: m68k-unknown-linux-gnu: zstd-1.4.9 test suite fails badly
I've been trying to build zstd on m68k-unknown-linux-gnu (since it is a dependency of the Gentoo package manager). (More precisely, a qemu-user chroot, but that should not have too much impact here.)

Unfortunately, while the build itself runs fine and the command line utility seems to start, the results in the zstd-1.4.9 testsuite look rather messy.
(1.5.0 does not work at all, bailing out with a "generic error").

I've attached the test log. Advice on how serious this is would be appreciated...

[build.log](https://github.com/facebook/zstd/files/7071186/build.log)

### PR DESCRIPTION
**Pull request by Cyan4973**
fix #2756

### CODE REVIEW

File: lib/common/mem.h [hunk 1]
```diff
@@ -80,6 +80,26 @@ extern "C" {
...
+#include <stdalign.h>
+# define MEM_ALIGN_COND(T) alignof(T)
+
+#elif defined(__GNUC__) || defined(_MSC_VER)
+
+# define MEM_ALIGN_COND(T) __alignof(T)
+
+#else
+
+# define MEM_ALIGN_COND(T) 1  /* most likely incorrect, just to pass tests */
```
Comment (terrelln) [inline lib/common/mem.h]: Won't this break some of the alignment in `huf_compress.c` on non-supported compilers?

Could we maybe default to `MIN(roundUpToPow2(sizeof(T)), sizeof(size_t))`?

**Review by terrelln — APPROVED** [review]
